import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1280,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
try{
    await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.gs);
    const results=await page.evaluate(async()=>{
        const engine=window.gs.engine;const rows=[];
        const open=async(path)=>{const start=performance.now();const result=await engine.open({kind:'url',url:new URL('/models/'+path,location.href).href}).result;rows.push({model:path,result,ms:performance.now()-start,snapshot:engine.getSnapshot()});return result;};
        let result=await open('changjin_v1.ply');if(!result.ok)throw Error(JSON.stringify(result));
        const count=engine.getSnapshot().sceneCount;
        result=await engine.open({kind:'blob',blob:new Blob(['bad'])}).result;
        if(result.ok||engine.getSnapshot().sceneCount!==count)throw Error('Failed replacement lost old scene');
        const operation=engine.open({kind:'url',url:new URL('/models/spz/jiulonghu_v1.spz',location.href).href});operation.cancel();result=await operation.result;
        if(result.ok||result.error.code!=='Cancelled'||engine.getSnapshot().sceneCount!==count)throw Error('Cancel did not retain active scene');
        engine.resize(800,600);engine.camera.orbit(100,20);engine.requestFrame();await new Promise(r=>setTimeout(r,100));
        result=await open('spz/shengyi_v1.spz');if(!result.ok)throw Error(JSON.stringify(result));
        const pose=engine.camera.getPose();result=await engine.recover();if(!result.ok||engine.getSnapshot().sceneCount!==804758||JSON.stringify(engine.camera.getPose())!==JSON.stringify(pose))throw Error('Recovery failed');
        rows.push({recovery:true,result,generation:engine.getSnapshot().deviceGeneration});
        const subscribers=[];const bad=engine.subscribe(()=>{throw Error('observer');});const good=engine.subscribe(()=>subscribers.push(1));
        engine.resize(900,600);bad();good();if(!subscribers.length)throw Error('Observer isolation failed');
        const invalid=await engine.open({kind:'url',url:'file:///not-a-model.ply'}).result;
        if(invalid.ok||invalid.error.code!=='InvalidInput'||engine.getSnapshot().sceneCount!==804758)throw Error('URL policy');
        const names=['x','y','z','f_dc_0','f_dc_1','f_dc_2','opacity','scale_0','scale_1','scale_2','rot_0','rot_1','rot_2','rot_3'];
        const header=new TextEncoder().encode('ply\nformat binary_little_endian 1.0\nelement vertex 1\n'+names.map(n=>'property float '+n+'\n').join('')+'end_header\n');
        const fixture={kind:'blob',blob:new Blob([header,new Float32Array([0,0,0,0,0,0,0,-2,-2,-2,1,0,0,0])])};
        const canvas=document.createElement('canvas');canvas.width=canvas.height=0;document.body.append(canvas);
        const created=await window.gs.createEngine({canvas,assets:{baseUrl:new URL('/assets/',location.href)},limits:{timeoutMs:3000}});
        if(!created.ok)throw Error(JSON.stringify(created));const hidden=created.value;
        const pending=hidden.open(fixture);await new Promise(r=>setTimeout(r,300));
        if(hidden.getSnapshot().sceneCount||hidden.getSnapshot().phase!=='Uploading')throw Error('Zero viewport activated');
        hidden.resize(64,64);const activated=await pending.result;if(!activated.ok)throw Error(JSON.stringify(activated));
        hidden.resize(0,0);const timed=await hidden.open(fixture).result;
        if(timed.ok||timed.error.code!=='Timeout'||hidden.getSnapshot().sceneCount!==1)throw Error('Zero viewport deadline');
        hidden.resize(64,64);
        hidden.renderer.device.dispatchEvent(new GPUUncapturedErrorEvent('uncapturederror',{error:new GPUValidationError('injected validation event')}));
        if(hidden.getSnapshot().phase!=='Faulted')throw Error('Injected fault was ignored');
        const rejected=await hidden.open(fixture).result;if(rejected.ok||rejected.error.code!=='DeviceLost'||hidden.getSnapshot().phase!=='Faulted')throw Error('Faulted open');
        const recovered=await hidden.recover();if(!recovered.ok||hidden.getSnapshot().phase!=='Ready')throw Error('Injected fault recovery');
        rows.push({browserBoundaryFixtures:{invalidUrl:invalid,zeroViewport:activated,timeout:timed,injectedFault:rejected,recovery:recovered,generation:hidden.getSnapshot().deviceGeneration},hardwareLossInjected:false});
        await hidden.dispose();canvas.remove();
        const tightCanvas=document.createElement('canvas');tightCanvas.width=tightCanvas.height=64;
        const tightResult=await window.gs.createEngine({canvas:tightCanvas,assets:{baseUrl:new URL('/assets/',location.href)},limits:{gpuBytes:1100}});
        if(!tightResult.ok)throw Error(JSON.stringify(tightResult));const tight=tightResult.value;tight.pause();
        if(!(await tight.open(fixture).result).ok)throw Error('Tight baseline rejected');
        const queue=tight.renderer.device.queue,original=queue.onSubmittedWorkDone.bind(queue);let release;
        queue.onSubmittedWorkDone=()=>new Promise(resolve=>{release=resolve;});
        const closing=tight.closeScene();const beforeRelease=await tight.open(fixture).result;
        if(beforeRelease.ok||beforeRelease.error.code!=='ResourceLimit')throw Error('Detached GPU budget bypass');
        queue.onSubmittedWorkDone=original;release();await closing;
        const afterRelease=await tight.open(fixture).result;if(!afterRelease.ok)throw Error('GPU reservation not released');
        rows.push({detachedGpuBudget:{beforeRelease,afterRelease}});await tight.dispose();
        const cpuCanvas=document.createElement('canvas');cpuCanvas.width=cpuCanvas.height=64;
        const cpuResult=await window.gs.createEngine({canvas:cpuCanvas,assets:{baseUrl:new URL('/assets/',location.href)},limits:{cpuBytes:80*2**20}});
        if(!cpuResult.ok)throw Error(JSON.stringify(cpuResult));const cpu=cpuResult.value;cpu.pause();
        const generated=count=>{
            const h=new TextEncoder().encode('ply\nformat binary_little_endian 1.0\nelement vertex '+count+'\n'+names.map(n=>'property float '+n+'\n').join('')+'end_header\n');
            const values=new Float32Array(count*14);for(let i=0;i<count;i++)values.set([(i%512)*.01,Math.floor(i/512)*.01,0,0,0,0,0,-7,-7,-7,1,0,0,0],i*14);
            return {kind:'blob',blob:new Blob([h,values])};
        };
        const larger=generated(150000);if(!(await cpu.open(generated(100000)).result).ok)throw Error('CPU baseline rejected');
        const cpuQueue=cpu.renderer.device.queue,cpuOriginal=cpuQueue.onSubmittedWorkDone.bind(cpuQueue);let cpuRelease;
        cpuQueue.onSubmittedWorkDone=()=>new Promise(resolve=>{cpuRelease=resolve;});const cpuClosing=cpu.closeScene();
        const cpuBefore=await cpu.open(larger).result;
        if(cpuBefore.ok||cpuBefore.error.code!=='ResourceLimit')throw Error('Detached CPU budget bypass');
        cpuQueue.onSubmittedWorkDone=cpuOriginal;cpuRelease();await cpuClosing;
        const cpuAfter=await cpu.open(larger).result;if(!cpuAfter.ok)throw Error('CPU reservation not released');
        rows.push({detachedCpuBudget:{budget:80*2**20,beforeRelease:cpuBefore,afterRelease:cpuAfter}});await cpu.dispose();
        return rows;
    });
    await page.screenshot({path:'test-results/real-model.png'});
    const shutdown=await page.evaluate(async()=>{const e=window.gs.engine;await e.closeScene();if(e.getSnapshot().sceneCount!==0)throw Error('close');await e.dispose();await e.dispose();return e.getSnapshot();});
    assert.equal(shutdown.phase,'Stopped');assert.deepEqual(errors,[]);
    await mkdir('docs/verification/evidence',{recursive:true});await writeFile('docs/verification/evidence/integration-tests.json',JSON.stringify({results,shutdown,errors},null,2));console.log(JSON.stringify({results,shutdown}));
}catch(reason){console.error('Browser errors',errors);throw reason;}finally{await browser.close();}
